---
- name: Set up Ansible groups.
  hosts: all

  tasks:
    # - ansible.builtin.gather_facts:
    #     parallel: yes
    - ansible.builtin.group_by:
        key: '{{ ansible_machine | lower }}'
    - ansible.builtin.debug: msg='{{ ansible_machine | lower }}'
    - ansible.builtin.group_by:
        key: '{{ ansible_os_family | lower | replace(" ","") }}_family'
    - ansible.builtin.debug: msg='{{ ansible_os_family | lower | replace(" ","") }}_family'
