---
- name: Install Caddy on all dedicated hosts.
  become: true
  hosts: dedicated

  vars:
    - caddy_version: 2.4.5
    - caddy_armv6_deb: caddy_{{ caddy_version }}_linux_armv6.deb
    - caddy_armv6_deb_url: 'https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/{{ caddy_armv6_deb }}'
    - caddy_config_path: /etc/caddy/Caddyfile

  roles:
    - role: nvjacobo.caddy

  tasks:
    - name: Download Caddy for Debian ARMv6
      ansible.builtin.get_url: 
        url="{{ caddy_armv6_deb_url }}"
        dest="/tmp/{{ caddy_armv6_deb }}"
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'armv6l'

    - name: Install Caddy for Debian ARMv6
      ansible.builtin.apt: deb="/tmp/{{ caddy_armv6_deb }}"
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'armv6l'

    - name: Configure Caddy to serve Cockpit subdomain with valid SSL cert.
      # https://caddy.community/t/example-cockpit/8283
      ansible.builtin.template:
        src: templates/caddy/cockpit-subdomain-config.j2
        dest: '{{ caddy_config_path }}'
        owner: root
        group: root
        mode: '0644'
      register: caddy_cockpit_subdomain_config

    - name: Restart Caddy if config has changed.
      ansible.builtin.service:
        name: caddy
        state: restarted
      when: caddy_cockpit_subdomain_config.changed
