---
- name: Install core utility packages on dedicated hosts.
  become: true
  hosts: dedicated

  tasks:
    - name: Ensure core utils are installed and up-to-date.
      ansible.builtin.package:
        name:
          - cloud-utils
          - iputils-ping
          - nmap
        state: latest

