---
- ansible.builtin.import_playbook: ansible-group-setup.yml

- hosts: all

  vars:
    distribution: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"

  tasks:
    - debug: var=ansible_facts['architecture']
    - debug: var=ansible_facts['machine']
    - debug: var=ansible_facts['os_family']
    - debug: var=distribution
    - debug: var=firewall_allowed_tcp_ports
    - debug: var=firewall_allowed_udp_ports
