---
- name: debug info for dedicated hosts
  hosts: [ dedicated, devel ]
  gather_facts: false
  tags: [ always ]

  vars_files:
    - vars/main.yml

  vars:
    distribution: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"

  tasks:
    - name: architecture
      ansible.builtin.debug: var=ansible_facts['architecture']
    - name: machine
      ansible.builtin.debug: var=ansible_facts['machine']
    - name: os_family
      ansible.builtin.debug: var=ansible_facts['os_family']
    - name: group_names
      ansible.builtin.debug: var=group_names
    #- name: groups
    #  ansible.builtin.debug: var=groups
    - name: ansible_run_tags
      ansible.builtin.debug: var=ansible_run_tags
    - name: distribution
      ansible.builtin.debug: var=distribution
    - name: firewall_allowed_tcp_ports
      ansible.builtin.debug: var=firewall_allowed_tcp_ports
    - name: firewall_allowed_udp_ports
      ansible.builtin.debug: var=firewall_allowed_udp_ports

    - name: ansible_facts for inventory host names specified in tags in addition to 'ansible_facts' tag
      ansible.builtin.debug: var=ansible_facts
      when: "inventory_hostname_short in ansible_run_tags"
      tags: [ never, ansible_facts ]

  pre_tasks:
    - name: Gather facts for all dedicated and development hosts in inventory.
      ansible.builtin.gather_facts:
        parallel: true
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - when: "'termux' in group_names"
      tags: [ termux, meta, infrastructure, infra, always ]
      block:
      - name: Check if python-apt is installed on Termux hosts.
        ansible.builtin.shell:
          cmd: 'python -c "import apt"'
        register: python_apt_is_installed
        changed_when: python_apt_is_installed.rc != 0
        failed_when: false
      - name: Install python-apt on Termux hosts.
        ansible.builtin.include_tasks: tasks/termux/install-python-apt.yml
        when: "python_apt_is_installed.rc != 0"

    - name: Gather package facts for all hosts in inventory.
      ansible.builtin.package_facts:
        manager: auto
        strategy: all
      failed_when: false # Fails on Chromium OS and derivatives
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - ansible.builtin.import_tasks: tasks/setup-ansible-groups.yml
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - ansible.builtin.include_tasks: tasks/meta/compile-lists.yml
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - name: Load Nebula configuration variables.
      ansible.builtin.include_vars: vars/nebula.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration

    - name: Load Yggdrasil configuration variables.
      ansible.builtin.include_vars: vars/yggdrasil.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration

    - name: Load Caddy configuration variables.
      ansible.builtin.include_vars: vars/caddy.yml
      vars:
        group_name: caddy_server
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration

    - name: Load Cockpit configuration variables.
      ansible.builtin.include_vars: vars/cockpit.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration

    - name: Load Gitea configuration variables.
      ansible.builtin.include_vars: vars/gitea-server.yml
      vars:
        group_name: META__gitea_server
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration

    - name: Load Minecraft Bedrock Server configuration variables.
      ansible.builtin.include_vars: families/paakaa.family/vars/minecraft-bedrock-server.yml
      vars:
        group_name: META__minecraft_bedrock_server
      when: "group_name in group_names or group_name in ansible_run_tags"
      tags:
        - configuration
