---
- name: Set up ILYfam cloud infrastructure.
  gather_facts: false # Facts are gathered in pre_tasks.
  hosts: all

  vars_files:
    - vars/main.yml

  tasks:
    - ansible.builtin.include_tasks: tasks/security.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - security
        - firewall

    - ansible.builtin.import_tasks: tasks/core-utils.yml
      tags:
        - infra
        - infrastructure
        - core_utils
        - coreutils
        - core
        - utils
        - packages
        - installation

    - ansible.builtin.include_tasks: tasks/ddclient.yml
      vars:
        group_name: remote_dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - remote
        - remote_dedicated
        - networking
        - dns
        - dynamic_dns
        - ddclient

    - ansible.builtin.include_tasks: tasks/nebula.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - networking
        - dns
        - mesh
        - vpn
        - firewall
        - nebula

    - ansible.builtin.include_tasks: tasks/yggdrasil.yml
      vars:
        group_name: yggdrasil
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - networking
        - mesh
        - firewall
        - yggdrasil

    - ansible.builtin.include_tasks: tasks/docker.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - containers
        - firewall
        - docker

    - ansible.builtin.include_tasks: tasks/ansible.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - automation
        - meta
        - viral
        - ansible

    - ansible.builtin.include_tasks: tasks/nodejs.yml
      when: "'dedicated' in group_names or 'shared' in group_names"
      tags:
        - infra
        - infrastructure
        - installation
        - packages
        - languages
        - javascript
        - nodejs

    - ansible.builtin.include_tasks: tasks/caddy.yml
      vars:
        group_name: caddy_server
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - servers
        - reverse_proxy
        - web
        - tcp
        - caddy

    - ansible.builtin.include_tasks: tasks/cockpit.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - servers
        - admin
        - observability
        - reverse_proxy
        - caddy
        - cockpit

    - ansible.builtin.include_tasks: tasks/db/main.yml
      vars:
        group_name: dedicated
      when: "group_name in group_names"
      tags:
        - infra
        - infrastructure
        - dedicated
        - servers
        - database
        - db
        - reverse_proxy
        - caddy

  pre_tasks:
  # IMPORTANT: Please add any tasks in this pre_tasks section to the pre_tasks section
  #            of debug-info.yml for environment parity.

    - name: Gather facts for all hosts in inventory.
      ansible.builtin.gather_facts:
        parallel: true
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - when: "'termux' in group_names"
      tags: [ termux, meta, infrastructure, infra, always ]
      block:
      - name: Check if python-apt is installed on Termux hosts.
        ansible.builtin.shell:
          cmd: 'python -c "import apt"'
        register: python_apt_is_installed
        changed_when: python_apt_is_installed.rc != 0
        failed_when: false
      - name: Install python-apt on Termux hosts.
        ansible.builtin.include_tasks: tasks/termux/install-python-apt.yml
        when: "python_apt_is_installed.rc != 0"

    - name: Gather package facts for all hosts in inventory.
      ansible.builtin.package_facts:
        manager: auto
        strategy: all
      failed_when: false # Fails on Chromium OS and derivatives
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - ansible.builtin.import_tasks: tasks/setup-ansible-groups.yml
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - ansible.builtin.import_tasks: tasks/meta/compile-lists.yml
      tags:
        - always
        - infra
        - infrastructure
        - meta

    - ansible.builtin.import_tasks: tasks/upgrade-all.yml
      tags:
        - infra
        - infrastructure
        - packages
        - upgrade

  post_tasks:
    - name: Install Gitea and set up Nebula forwarding for Gitea via Caddy.
      ansible.builtin.include_tasks: tasks/gitea-server.yml
      when: "'META__gitea_server' in group_names"
      tags:
        - infra
        - infrastructure
        - servers
        - reverse_proxy
        - caddy
        - git
        - gitea

- name: Run playbooks for all participant families.
  ansible.builtin.import_playbook: families/main.yml
  tags:
    - families
