---
- name: Install Minecraft Bedrock Server
  hosts: minecraft_bedrock_server

  vars:
    port_ipv4: 19132
    port_ipv6: 19133

    server_name: "{{ paakaa_family_cloud_name }} MC"
    level_name: "CP ~ Creative & Peaceful"
    game_mode: "creative"
    difficulty: "peaceful"

  tasks:
    - name: "Ensure Docker volume for Minecraft Bedrock Server named {{ server_name | quote }} is created."
      community.docker.docker_volume:
        name: minecraft_bedrock_server_volume

    - name: "Ensure Docker container for Minecraft Bedrock Server named {{ server_name | quote }} hosting level named {{ level_name | quote }} is started."
      community.docker.docker_container:
        name: minecraft-bedrock-server
        image: itzg/minecraft-bedrock-server:latest
        pull: true
        state: started
        restart_policy: always
        container_default_behavior: "compatibility"
        ports:
          - "{{ port_ipv4 }}:{{ port_ipv4 }}/udp"
          - "{{ port_ipv6 }}:{{ port_ipv6 }}/udp"
        env:
          EULA: "TRUE"
          VERSION: "LATEST"
          SERVER_PORT: "{{ port_ipv4 | quote }}"
          SERVER_PORT_V6: "{{ port_ipv6 | quote }}"
          SERVER_NAME: "{{ server_name }}"
          LEVEL_NAME: "{{ level_name }}"
          GAMEMODE: "{{ game_mode }}"
          DIFFICULTY: "{{ difficulty }}"
          SERVER_AUTHORITATIVE_MOVEMENT: "server-auth-with-rewind"
          CORRECT_PLAYER_MOVEMENT: "true"
          SERVER_AUTHORITATIVE_BLOCK_BREAKING: "true"
        volumes:
          - minecraft_bedrock_server_volume:/data
