---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.firewall
  - name: adamruzicka.ansible_yggdrasil
  - name: geerlingguy.nodejs
  - name: geerlingguy.pip
  - name: geerlingguy.ansible
  - name: geerlingguy.docker
  - name: mivek.ddclient
  - name: trozz.ansible_nebula
  - name: nvjacobo.caddy

collections:
  - name: community.general
  - name: ansible.posix
  - name: community.docker
  - name: chocolatey.chocolatey
