---
- hosts: all
- ansible.builtin.import_playbook: ansible-group-setup.yml
- ansible.builtin.import_playbook: upgrade-crew.yml
- ansible.builtin.import_playbook: upgrade-choco.yml
- ansible.builtin.import_playbook: upgrade-apt.yml
