---
- name: Install Yggdrasil on dedicated hosts.
  become: true
  hosts: dedicated

  roles:
    - adamruzicka.ansible_yggdrasil

  # TODO: in /etc/yggdrasil.conf, collect PublicKey from all dedicated hosts and add to AllowedPublicKeys on all other dedicated hosts
  #       possible with an inventory plugin?
