---
- tags: [ database, db ]
  block:

  - name: Set up PostgreSQL.
    ansible.builtin.include_tasks: postgresql.yml
    vars:
      group_name: postgresql
    when: "group_name in group_names"
    tags: [ postgres, postgresql ]

  - name: Set up Adminer.
    ansible.builtin.include_tasks: adminer.yml
    vars:
      group_name: META__adminer
    when: "group_name in group_names"
    tags: [ admin, reverse_proxy, caddy, adminer ]
