---
all:
  children:

##############################
##### Development groups #####
##############################
    devel:
      hosts:
        chromebook:
        chromebook-termux:

    chromiumos_family:
      children:
        chromiumos:
        chromeos_family:

    chromeos_family:
      children:
        chromeos:

    termux:
      hosts:
        chromebook-termux:

    PKG__crew:
      children:
        chromiumos_family:

####################################
##### Solution-oriented groups #####
####################################
    caddy_server:
      hosts:
        chromebook-termux:

#####
##### Make sure these groups stay last in this section!
#####
    yggdrasil:
      hosts:
        chromebook-termux:
