---
all:
  children:

########################
##### Local groups #####
########################
    bare_metal:
      children:
        pi:

    pi:
      children:
        raspberry_pi:
        atomic_pi:

    local_dedicated:
      children:
        pi:

    local:
      children:
        local_dedicated:

#########################
##### Remote groups #####
#########################
    cloud:
      children:
        google_cloud:
        oracle_cloud:

    remote_dedicated:
      children:
        google_cloud:
        oracle_cloud:

    remote_shared:
      children:
        dreamhost_shared:

    remote:
      children:
        remote_dedicated:
        remote_shared:

######################################
##### Hybrid local/remote groups #####
######################################
    dedicated:
      children:
        local_dedicated:
        remote_dedicated:

    shared:
      children:
        remote_shared:

####################################
##### Solution-oriented groups #####
####################################
    caddy_server:
      children:
        dedicated:

    postgresql:
      hosts:
        paakaa-pi-0:

    adminer:
      hosts:
        paakaa-pi-0:
    adminer_proxy:
      children:
        remote_dedicated:
    META__adminer:
      children:
        adminer:
        adminer_proxy:

    gitea:
      hosts:
        paakaa-pi-0:
    gitea_proxy:
      children:
        remote_dedicated:
    META__gitea:
      children:
        gitea:
        gitea_proxy:

#####
##### Make sure these groups stay last in this section!
#####
    nebula_lighthouse:
      children:
        remote_dedicated:

    yggdrasil:
      children:
        dedicated:

##########################################################
##### Machine OS/package manager/architecture groups #####
##### ---------------------------------------------- #####
##### Run debug-info.yml playbook to get information #####
##### for updating this section.                     #####
##########################################################
    debian_family:
      children:
        debian:
        ubuntu:

    PKG__choco:
      children:
        windows:

    arm64:
      children:
        aarch64:

    arm32:
      children:
        armv6l:

    amd64:
      children:
        x86_64:

    x86:
      children:
        i386:

    amd32:
      children:
        x86:
