---
all:
  children:
    chromeos:
      hosts:
        chromebook:

    debian_family:
      hosts:
        paakaa-pi-0:
        paakaa-pi-1:
        paakaa-pi-2:
        gcp-free:
        oci-free-0:
        oci-free-1:
        oci-free-2:
        oci-free-3:
        oci-free-4:
        oci-free-5:
        dreamhost-shared:

    google_cloud:
      hosts:
        gcp-free: # always-free

    oracle_cloud:
      hosts:
        oci-free-0: # always-free
        oci-free-1: # always-free
        oci-free-2: # always-free
        oci-free-3: # always-free
        oci-free-4: # always-free
        oci-free-5: # always-free

    dreamhost_shared:
      hosts:
        dreamhost-shared:

    local:
      hosts:
        chromebook:
        paakaa-pi-0:
        paakaa-pi-1:
        paakaa-pi-2:

    remote_dedicated:
      children:
        google_cloud:
        oracle_cloud:

    remote_shared:
      children:
        dreamhost_shared:

    remote:
      children:
        remote_dedicated:
        remote_shared:

    raspberry_pi:
      hosts:
        paakaa-pi-0:
        paakaa-pi-1:

    atomic_pi:
      hosts:
        paakaa-pi-2:

    pi:
      children:
        raspberry_pi:
        atomic_pi:

    dedicated:
      children:
        pi:
        remote_dedicated:

    not_chromebook:
      children:
        pi:
        remote:

    arm64:
      hosts:
        paakaa-pi-0:

    arm32:
      hosts:
        paakaa-pi-1:

    amd64:
      hosts:
        chromebook:
        paakaa-pi-2:

    minecraft_bedrock_server:
      hosts:
        paakaa-pi-2:

    nebula_lighthouse:
      children:
        dedicated:
