---
all:
  children:

##### Local groups
    local:
      hosts:
        chromebook:
        paakaa-pi-0:
        paakaa-pi-1:
        paakaa-pi-2:

    raspberry_pi:
      hosts:
        paakaa-pi-0:
        paakaa-pi-1:

    atomic_pi:
      hosts:
        paakaa-pi-2:

    pi:
      children:
        raspberry_pi:
        atomic_pi:

    local_dedicated:
      children:
        pi:

##### Remote groups
    google_cloud:
      hosts:
        gcp-free: # always-free

    oracle_cloud:
      hosts:
        oci-free-0: # always-free
        oci-free-1: # always-free
        oci-free-2: # always-free
        oci-free-3: # always-free
        oci-free-4: # always-free
        oci-free-5: # always-free

    dreamhost_shared:
      hosts:
        dreamhost-shared:

    remote_dedicated:
      children:
        google_cloud:
        oracle_cloud:

    remote_shared:
      children:
        dreamhost_shared:

    remote:
      children:
        remote_dedicated:
        remote_shared:

##### Hybrid local/remote groups
    dedicated:
      children:
        local_dedicated:
        remote_dedicated:

##### Solution-oriented groups
    gitea_server:
      hosts:
        paakaa-pi-0:
    gitea_server_proxy:
      hosts:
        gcp-free:

    minecraft_bedrock_server:
      hosts:
        paakaa-pi-2:

    minecraft_bedrock_server_proxy:
      hosts:
        gcp-free:

    # Make sure nebula_lighthouse group stays last!
    nebula_lighthouse:
      children:
        remote_dedicated:

##### Machine distro/architecture alias groups
    chromeos:
      children:
        chromeos_family:

    arm64:
      children:
        aarch64:

    arm32:
      children:
        armv6l:

    amd64:
      children:
        x86_64:
