---
- name: Load Caddy configuration variables.
  ansible.builtin.include_vars: vars/caddy.yml
  tags:
    - configuration

- name: Install Caddy.
  become: true
  ansible.builtin.import_role:
    name: nvjacobo.caddy
  tags:
    - installation
    - sudo

- name: Download Caddy for Debian ARMv6.
  become: true
  ansible.builtin.get_url:
    url="{{ caddy_armv6_deb_url }}"
    dest="/tmp/{{ caddy_armv6_deb }}"
  when: "ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'armv6l'"
  tags:
    - installation
    - sudo

- name: Install Caddy for Debian ARMv6.
  become: true
  ansible.builtin.apt: deb="/tmp/{{ caddy_armv6_deb }}"
  when: "ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'armv6l'"
  tags:
    - installation
    - sudo

- name: Initialize Caddy config if it's missing.
  become: true
  ansible.builtin.template:
    src: templates/caddy/init.j2
    dest: '{{ caddy_config_path }}'
    owner: root
    group: root
    mode: '0644'
    force: false
  tags:
    - configuration
    - sudo
