---
- tags: [ infra, infrastructure, core_utils, coreutils, core, utils, packages, installation ]
  block:

  - ansible.builtin.include_tasks: tasks/core-utils-debian.yml
    vars:
      group_name: debian_family
    when: "group_name in group_names and can_sudo"
    tags: [ debian, debian_family, apt ]

  - ansible.builtin.include_tasks: tasks/core-utils-termux.yml
    vars:
      group_name: termux
    when: "group_name in group_names"
    tags: [ termux, apt ]
