---
- ansible.builtin.import_tasks: tasks/core-utils-debian.yml
  vars:
    group_name: debian_family
  when: "group_name in group_names"
  tags:
    - infra
    - infrastructure
    - dedicated
    - core
    - utils
    - packages

- ansible.builtin.import_tasks: tasks/core-utils-termux.yml
  vars:
    group_name: termux
  when: "group_name in group_names"
  tags:
    - infra
    - infrastructure
    - dedicated
    - core
    - utils
    - packages
