---
- name: Install and configure ddclient for dynamic DNS resolution.
  become: true
  ansible.builtin.import_role:
    name: mivek.ddclient
  vars:
    daemon: 0
    configs:
      - 
        protocol: googledomains
        ssl: yes
        use: web
        server: domains.google.com
        backupmx: null
        mx: null
        mxpri: null
        wildcard: null
        login: '{{ google_domains_username }}' # from inventory/host_vars/{{ inventory_hostname_short }}.yml
        password: '{{ google_domains_password }}' # from inventory/host_vars/{{ inventory_hostname_short }}.yml
        hosts:
          - '{{ host_fqdn }}'
  tags:
    - installation
    - packages
    - configuration
    - dns
    - sudo

- name: Force-update dynamic DNS entry.
  become: true
  ansible.builtin.command: ddclient -daemon=0 -verbose -force
  tags:
    - configuration
    - dns
    - sudo
