---
- name: Ensure pip is installed and install pip package for Docker.
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
  tags:
    - installation
    - pip
    - containers
    - docker
    - sudo

- name: Install Docker and Docker Compose.
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    # Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: latest
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose: true
    docker_compose_version: "1.29.2"
    docker_compose_path: /usr/local/bin/docker-compose
  tags:
    - installation
    - packages
    - containers
    - docker
    - sudo
