---
- tags: [ servers, git, gitea ]
  block:

  - name: Load Gitea configuration variables.
    ansible.builtin.include_vars: vars/gitea.yml
    tags: [ configuration, reverse_proxy, caddy ]

    # TODO: convert to use Docker module directly, migrate data from filesystem mount to Docker volume, and get volume backed up
  - name: Install Gitea.
    ansible.builtin.include_role:
      name: salessandri.gitea
      apply:
        become: true
        vars:
          gitea__ssh_port: '{{ tcp_port_ssh_gitea }}'
          gitea__web_host: '{{ nebula.nebula_ip }}'
          gitea__web_port: '{{ tcp_port_http_gitea }}'
          gitea__hostname: '{{ gitea_fqdn }}'
          gitea__root_url: 'https://{{ gitea_fqdn }}/'
          gitea__enable_lfs: true
          gitea__app_name: '{{ gitea_app_name }}'
    when: "'gitea' in group_names"
    tags: [ sudo, installation, configuration, containers, docker ]

  - name: Add reverse proxy block to Caddyfile for Gitea.
    become: true
    ansible.builtin.blockinfile:
      path: '{{ caddy_config_path }}'
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GITEA"
      block: "{{ lookup('template', 'templates/caddy/gitea.j2') }}" # https://garthkerr.com/using-ansible-template-for-partial-file-block/
    register: caddy_gitea_subdomain_config
    when: "'gitea_proxy' in group_names"
    tags: [ sudo, configuration, reverse_proxy, caddy ]

  - name: Reload Caddy if config has changed.
    become: true
    ansible.builtin.service:
      name: caddy
      enabled: true
      state: reloaded
    when: "'gitea_proxy' in group_names and caddy_gitea_subdomain_config.changed"
    tags: [ sudo, configuration, reverse_proxy, caddy ]
