---
- name: Load Nebula configuration variables.
  ansible.builtin.include_vars: vars/nebula.yml
  tags:
    - configuration

- name: Populate list of lighthouses.
  ansible.builtin.set_fact:
    lighthouses: "{{ groups['nebula_lighthouse'] | map('extract', hostvars, ['nebula']) | list }}"
  tags:
    - configuration

- name: Create Nebula Certificate Authority.
  local_action:
    module: ansible.builtin.command
    chdir: files/nebula/
    cmd: 'nebula-cert ca -name "{{ family_cloud_name }}"'
    creates: ca.key
  failed_when: false
  tags:
    - configuration

- name: Decrypt Nebula Certificate Authority files.
  local_action:
    module: ansible.builtin.command
    cmd: 'ansible-vault decrypt files/nebula/ca.crt files/nebula/ca.key'
  failed_when: false
  tags:
    - configuration

- name: Create Nebula certificates.
  local_action:
    module: ansible.builtin.command
    chdir: files/nebula/
    cmd: 'nebula-cert sign -name "{{ nebula.external_addr }}" -ip "{{ nebula.nebula_ip }}/24"'
    creates: "{{ nebula.external_addr }}.crt"
  register: nebula_certificate_create
  tags:
    - configuration

- name: Encrypt Nebula Certificate Authority files.
  local_action:
    module: ansible.builtin.command
    cmd: 'ansible-vault encrypt --encrypt-vault-id {{ family_domain }} files/nebula/ca.crt files/nebula/ca.key'
  failed_when: false
  tags:
    - configuration

- name: Encrypt Nebula certificates.
  local_action:
    module: ansible.builtin.command
    cmd: 'ansible-vault encrypt --encrypt-vault-id {{ family_domain }} files/nebula/{{ nebula.external_addr }}.crt files/nebula/{{ nebula.external_addr }}.key'
  when: nebula_certificate_create.changed
  tags:
    - configuration

- name: Create Nebula directory.
  become: true
  ansible.builtin.file:
    path: '{{ nebula_directory }}'
    state: directory
    mode: '0750'
  tags:
    - configuration
    - sudo

- name: Deploy Nebula certificates.
  become: true
  ansible.builtin.copy:
    src: 'files/nebula/{{ item }}'
    dest: '{{ nebula_directory }}/{{ item }}'
    owner: root
    group: root
    mode: '0600'
  with_items:
    - 'ca.crt'
    - '{{ nebula.external_addr }}.crt'
    - '{{ nebula.external_addr }}.key'
  tags:
    - configuration
    - sudo

- name: Download Nebula release from GitHub (arm6).
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/slackhq/nebula/releases/download/v{{ nebula_version }}/nebula-{{ ansible_system|lower }}-arm-6.tar.gz
    dest: /bin
    remote_src: yes
    mode: 0755
    creates: /bin/nebula
  when: "ansible_architecture.startswith('armv6')"
  tags:
    - installation
    - sudo

- name: Install and configure Nebula mesh VPN.
  become: true
  ansible.builtin.import_role:
    name: trozz.ansible_nebula
  tags:
    - installation
    - configuration
    - sudo
