---
- tags: [ installation, packages, languages, javascript, nodejs ]
  block:

  - name: Install node.js on dedicated hosts or shared hosts with sudo.
    ansible.builtin.include_role:
      name: geerlingguy.nodejs
      apply:
        become: true
    when: "'dedicated' in group_names or ('shared' in group_names and can_sudo)"
    tags: [ sudo, dedicated, shared ]

  - name: Install node.js on Termux hosts.
    become: false
    ansible.builtin.apt:
      name: nodejs
      state: latest
    when: "'termux' in group_names"
    tags: [ termux ]

  # https://github.com/nvm-sh/nvm
  - name: Install Node Version Manager on shared hosts.
    become: false
    ansible.builtin.shell:
      cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
    vars:
      nvm_version: "0.38.0"
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    when: "'shared' in group_names and not can_sudo"
    tags: [ shared ]
