---
- name: Run Jeff Geerling's security role on dedicated hosts.
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.security
  vars:
    security_autoupdate_reboot: true
    security_autoupdate_mail_to: "maintainers@ilyfam.family"
    security_ssh_password_authentication: "yes" # SSH rules must be single-/double-quoted yes/no

- name: Run Jeff Geerling's firewall role on dedicated hosts.
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.firewall
  vars:
    firewall_flush_rules_and_chains: false # Docker
