---
- ansible.builtin.import_tasks: upgrade-crew.yml
  when: "'PKG__crew' in group_names"
  tags:
    #- never
    - chromebrew
    - crew

- ansible.builtin.import_tasks: upgrade-choco.yml
  when: "'PKG__choco' in group_names"
  tags:
    #- never
    - chocolatey
    - choco

- ansible.builtin.import_tasks: upgrade-apt.yml
  when: "'PKG__apt' in group_names"
  tags:
    #- never
    - aptitude
    - apt
