---
- tags: [ networking, mesh, firewall, yggdrasil ]
  block:

  - when: "'dedicated' in group_names"
    block:

    - name: Load Yggdrasil configuration variables.
      ansible.builtin.include_vars: vars/yggdrasil.yml
      tags: [ configuration ]

    - name: Reset Yggdrasil configuration to test installation procedure.
      tags: [ never, sudo, reset, remove, test ]
      when: "'reset' in ansible_run_tags or 'remove' in ansible_run_tags or 'test' in ansible_run_tags"
      become: true
      ansible.builtin.shell:
        cmd: 'yggdrasil -genconf -json > {{ yggdrasil_config_path }}'

    - name: Check if Yggdrasil is already installed.
      ansible.builtin.set_fact:
        yggdrasil_is_installed: "{{ ansible_facts['packages']['yggdrasil'] is defined }}"
      changed_when: not yggdrasil_is_installed

    - name: Install Yggdrasil.
      when: not yggdrasil_is_installed
      ansible.builtin.include_role:
        name: adamruzicka.ansible_yggdrasil
        apply:
          become: true
      tags: [ sudo, installation ]

    - name: Get Yggdrasil config from {{ yggdrasil_config_path }}.
      ansible.builtin.slurp:
        src: '{{ yggdrasil_config_path }}'
      register: yggdrasil_config
      tags: [ configuration ]

    - name: Set fact for Yggdrasil config from content of {{ yggdrasil_config_path }}.
      ansible.builtin.set_fact:
        yggdrasil_config: "{{ yggdrasil_config['content'] | b64decode }}"

    - name: Set fact for Yggdrasil Public Key from Yggdrasil config.
      ansible.builtin.set_fact:
        yggdrasil_public_key: '{{ yggdrasil_config.PublicKey }}'
      tags: [ configuration ]

  - name: "Yggdrasil Public Key is:"
    ansible.builtin.debug:
      var: yggdrasil_public_key
    tags: [ never, debug ]

  - name: "Yggdrasil peering addresses are:"
    ansible.builtin.debug:
      var: yggdrasil_peering_addresses
    tags: [ never, debug ]

  - name: "Hosts from '{{ group_name }}' group, from which to compile AllowedPublicKeys, Peers:"
    ansible.builtin.debug:
      var: groups[group_name]
    tags: [ never, debug ]

  - name: Compile Yggdrasil AllowedPublicKeys list from all '{{ group_name }}' hosts.
    ansible.builtin.set_fact:
      yggdrasil_allowed_public_keys: "{{ yggdrasil_allowed_public_keys + [ hostvars[host]['yggdrasil_public_key'] ] }}"
    when: host != inventory_hostname_short
    with_items: '{{ groups[group_name] }}'
    loop_control:
      loop_var: host

  - name: Compile Yggdrassil Peers list from all '{{ group_name }}' hosts.
    ansible.builtin.set_fact:
      yggdrasil_peers: "{{ yggdrasil_peers + hostvars[host]['yggdrasil_peering_addresses'] }}"
    when: host != inventory_hostname_short
    with_items: '{{ groups[group_name] }}'
    loop_control:
      loop_var: host

  - name: "Yggdrasil AllowedPublicKeys list is:"
    ansible.builtin.debug:
      var: yggdrasil_allowed_public_keys
    tags: [ never, debug ]

  - name: "Yggdrasil Peers list is:"
    ansible.builtin.debug:
      var: yggdrasil_peers
    tags: [ never, debug ]

  - when: "'dedicated' in group_names"
    block:

    - name: Update Yggdrasil config with current values for Allowed Public Keys, Peers, Listen, Multicast Interfaces.
      ansible.builtin.set_fact:
        yggdrasil_config: >-
          {{ yggdrasil_config | combine({ 'AllowedPublicKeys': yggdrasil_allowed_public_keys })
                              | combine({ 'Peers': yggdrasil_peers })
                              | combine({ 'Listen': yggdrasil_listen })
                              | combine({ 'MulticastInterfaces': yggdrasil_multicast_interfaces })
          }}
      tags: [ configuration ]

    - name: Write updated Yggdrasil config back to config file at {{ yggdrasil_config_path }}.
      become: true
      ansible.builtin.copy:
        content: '{{ yggdrasil_config | to_nice_json }}'
        dest: '{{ yggdrasil_config_path }}'
      tags: [ sudo, configuration ]

    - name: Reset Yggdrasil systemd "service failed" state.
      become: true
      ansible.builtin.shell:
        cmd: systemctl reset-failed yggdrasil
      changed_when: false
      tags: [ sudo, configuration ]

    - name: Reload Yggdrasil service after configuration changes.
      become: true
      ansible.builtin.service:
        name: yggdrasil
        enabled: true
        state: reloaded
      tags: [ sudo, configuration ]
