---
ansible_host: paakaa-pi-2.local
ansible_user: atomicpi

family_domain: paakaa.family

host_fqdn: "paakaa-pi-2.machines.{{ family_domain }}"

nebula:
  nebula_ip: 192.168.100.10
  external_addr: "9.nodes.nebula.{{ family_domain }}"
