---
ansible_host: paakaa-pi-1.local
ansible_user: pi

family_domain: paakaa.family

host_fqdn: "{{ inventory_hostname_short }}.machines.{{ family_domain }}"

nebula:
  nebula_ip: 192.168.100.9
  external_addr: "8.nodes.nebula.{{ family_domain }}"
