---
ansible_host: paakaa-pi-0.local
ansible_user: ubuntu

family_domain: paakaa.family

host_fqdn: "{{ inventory_hostname_short }}.machines.{{ family_domain }}"

nebula:
  nebula_ip: 192.168.100.8
  external_addr: "7.nodes.nebula.{{ family_domain }}"
