---
all:
  children:

########################
##### Local groups #####
########################
    raspberry_pi:
      hosts:
        paakaa-pi-0:
        paakaa-pi-1:

    atomic_pi:
      hosts:
        paakaa-pi-2:

#########################
##### Remote groups #####
#########################
    google_cloud:
      hosts:
        gcp-free-parker-christopher: # always-free

    oracle_cloud:
    # Each tenancy gets the first 3,000 OCPU hours and 18,000 GB hours per month
    # for free to create Ampere A1 Compute instances using the VM.Standard.A1.Flex shape
    # (equivalent to 4 OCPUs and 24 GB of memory).
    # Each tenancy also gets two VM.Standard.E2.1.Micro instances for free.
    # Learn more about Always Free resources:
    #   https://docs.oracle.com/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm
      hosts:
        oci-free-parker-christopher-0: # always-free
        oci-free-parker-christopher-1: # always-free
        oci-free-parker-christopher-2:
        oci-free-parker-christopher-3:
        oci-free-parker-christopher-4:
        oci-free-parker-christopher-5:

    dreamhost_shared:
      hosts:
        dreamhost-shared-parker-christopher:

####################################
##### Solution-oriented groups #####
####################################
    minecraft_bedrock_server:
      hosts:
        paakaa-pi-2:
    minecraft_bedrock_server_proxy:
      children:
        remote_dedicated:
    META__minecraft_bedrock_server:
      children:
        minecraft_bedrock_server:
        minecraft_bedrock_server_proxy:
