---
all:
  children:

########################
##### Local groups #####
########################
    raspberry_pi:
      hosts:
        paakaa-pi-0:
        paakaa-pi-1:

    atomic_pi:
      hosts:
        paakaa-pi-2:

#########################
##### Remote groups #####
#########################
    google_cloud:
      hosts:
        gcp-free-parker-christopher: # always-free

    oracle_cloud:
      hosts:
        oci-free-parker-christopher-0: # always-free
        oci-free-parker-christopher-1: # always-free
        oci-free-parker-christopher-2: # always-free
        oci-free-parker-christopher-3: # always-free
        oci-free-parker-christopher-4: # always-free
        oci-free-parker-christopher-5: # always-free

    dreamhost_shared:
      hosts:
        dreamhost-shared-parker-christopher:

####################################
##### Solution-oriented groups #####
####################################
    minecraft_bedrock_server:
      hosts:
        paakaa-pi-2:
    minecraft_bedrock_server_proxy:
      children:
        remote_dedicated:
    META__minecraft_bedrock_server:
      children:
        minecraft_bedrock_server:
        minecraft_bedrock_server_proxy:
