---
# Run this on Termux host to test:
#   apt remove git python gcc-11 -y && apt autoremove -y && rm ${PREFIX}/etc/apt/sources.list.d/pointless.list && rm -rf ${HOME}/src && apt update && apt install python -y

- name: Ensure python-apt v{{ python_apt_version }} is installed on Termux hosts.
  when: "'termux' in group_names"
  tags: [ termux ]

  vars:
    python_apt_version: 2.2.1

  block:

  - name: Check if python-apt is already installed.
    ansible.builtin.shell:
      cmd: 'python -c "import apt"'
    register: python_apt_is_installed
    changed_when: python_apt_is_installed.rc != 0
    failed_when: false

  - name: Install python-apt.
    when: python_apt_is_installed.rc != 0
    ansible.builtin.include_tasks: python-apt/install.yml
