---
- name: Ensure python-apt is installed on Termux hosts.
  ansible.builtin.include_tasks: tasks/termux/python-apt.yml
  tags: [ termux ]
  when: "'termux' in group_names"

- name: Update apt cache, upgrade apt packages, and autoremove packages no longer required.
  become: '{{ can_sudo }}'
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # one day
    autoremove: true
  when: "'PKG__apt' in group_names and ('shared' not in group_names or can_sudo or 'termux' in group_names)"
  tags:
    - termux
    - debian
    - debian_family
    - ubuntu
