---
- ansible.builtin.include_tasks: crew.yml
  when: "'PKG__crew' in group_names"
  tags:
    #- never
    - chromebrew
    - crew

- ansible.builtin.include_tasks: choco.yml
  when: "'PKG__choco' in group_names"
  tags:
    #- never
    - chocolatey
    - choco

- ansible.builtin.include_tasks: apt.yml
  when: "'PKG__apt' in group_names"
  tags:
    #- never
    - aptitude
    - apt
