---
- tags: [ core_utils, coreutils, core, utils, packages, installation, termux, apt ]
  block:

  - name: Ensure python-apt is installed on Termux hosts.
    ansible.builtin.include_tasks: tasks/termux/python-apt.yml

  - name: Ensure latest versions of core utility packages are installed on Termux hosts.
    become: false
    vars:
      # Please keep this list alphabetized.
      core_utils_termux:
      - gping
      - okc-agents
      - openssh
      - python # Python 3

      ### https://gist.github.com/oofnikj/e79aef095cd08756f7f26ed244355d62
      - qemu-common
      - qemu-system-x86_64-headless
      - qemu-utils

      - rust
      - termux-api

    ansible.builtin.apt:
        name: "{{ core_utils + core_utils_apt + core_utils_termux }}"
        state: latest
