---
can_sudo: false
ansible_python_interpreter: auto

family_domain: ilyfam.family

# Please keep this list alphabetized.
core_utils:
- cowsay
- curl
- git
- gnupg
- jq
- net-tools
- nano
- nmap
- tor
- vim
- wget
