---
# For geerlingguy.firewall role
firewall_allowed_tcp_ports_gitea:
- '{{ tcp_port_http_gitea }}'
- '{{ tcp_port_ssh_gitea }}'

# For trozz.ansible_nebula role
inbound_gitea:
- port: '{{ tcp_port_http_gitea }}'
  proto: tcp
  host: any

- port: '{{ tcp_port_ssh_gitea }}'
  proto: tcp
  host: any
