---
# For geerlingguy.firewall role
firewall_allowed_udp_ports:
  - '{{ udp_port_nebula }}'
  - '{{ udp_port_minecraft_bedrock_server_ipv4 }}'
  - '{{ udp_port_minecraft_bedrock_server_ipv6 }}'

# For trozz.ansible_nebula role
inbound:
  - port: any
    proto: icmp
    host: any

  - port: '{{ tcp_port_ssh }}'
    proto: tcp
    host: any

  - port: '{{ udp_port_minecraft_bedrock_server_ipv4 }}'
    proto: udp
    host: any

  - port: '{{ udp_port_minecraft_bedrock_server_ipv6 }}'
    proto: udp
    host: any
